version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.2
jobs:
  build-and-test:
    branches:
        only:
            - master
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm run build
            - run: npm test
      - store_artifacts:
            path: coverage
  publish:
    executor:
      name: node/default
    steps:
        - checkout
        - run:
            name: Publish to NPM
            command: |
                npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                npm publish

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - publish:
            filters:
                tags:
                    only: /v[0-9]+(\.[0-9]+)*/