name: build

on:
  push:
    branches: ['*', '!main']
    paths-ignore: ["**.md"]
  pull_request:
    branches: [main]
    paths-ignore: ["**.md"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Analyze, test and build codebase
        run: |
          npm install
          npm run lint
          npm test
          npm run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          fail_ci_if_error: false